FROM oven/bun:1.3.10

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./apps/web ./apps/web
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

RUN bun install

RUN bunx prisma generate --schema=./packages/db/prisma/schema.prisma

RUN bun run build

EXPOSE 3000

CMD ["bun", "run", "start:web"]