name: Deploy the backend 
on: 
  push: 
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code 
        uses: actions/Checkout@v2

      - name: Docker login
        uses: docker/login-action@v2 
        with:
          username: ${{ screts.DOCKERHUB_USERNAME }} 
          password: ${{ screts.DOCKERHUB_TOKEN }} 

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockefile.backend
          push: true
          tags: hitendras510/Todo-app-backend:${{ github.sha }}